### ISSUE TITLE
Update to Ruby 2.5.6

### ISSUE THREAD

**Issue by joesustaric** [brightbox/deb-ruby2.5#2]
Hi there,
https://www.ruby-lang.org/en/news/2019/08/28/ruby-2-5-6-released/

Includes fixes for https://www.ruby-lang.org/en/news/2019/08/28/multiple-jquery-vulnerabilities-in-rdoc/

An update would be appreciated.

Thanks!

**Comment by johnl** [comment]
done, 2.5.7 now.
